name: Test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5.x, 2.6.x]
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: setup gems
      run: |
        gem install bundler
        bundle install
    - name: run test and publish code coverage
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: bundle exec rake spec
        
