biblioentry = Biblioentry.find_by_xreflabel('holoceneeruptions')
Citation.create(:name => "HoloceneEruptions", :user_id => @user.id,:biblioentry_id => biblioentry.id)
@holoceneeruptions = Citation.find_by_name("HoloceneEruptions")
@holoceneeruption = @holoceneeruptions
biblioentry = Biblioentry.find_by_xreflabel('annalesulster')
Citation.create(:name => "AnnalesUlster", :user_id => @user.id,:biblioentry_id => biblioentry.id)
@annalesulster = Citation.find_by_name("AnnalesUlster")
biblioentry = Biblioentry.find_by_xreflabel('baillie1999')
Citation.create(:name => "Baillie1999", :user_id => @user.id,:biblioentry_id => biblioentry.id)
@baillie1999 = Citation.find_by_name("Baillie1999")
biblioentry = Biblioentry.find_by_xreflabel('OlympiaEarthquake')
Citation.create(:name => "OlympiaEarthquake", :user_id => @user.id,:biblioentry_id => biblioentry.id)
@olympiaearthquake = Citation.find_by_name("OlympiaEarthquake")
biblioentry = Biblioentry.find_by_xreflabel('cantor2001')
Citation.create(:name => "cantor2001", :user_id => @user.id,:biblioentry_id => biblioentry.id)
@cantor2001 = Citation.find_by_name("cantor2001")
biblioentry = Biblioentry.find_by_xreflabel('ziegler1969')
Citation.create(:name => "ziegler1969", :user_id => @user.id,:biblioentry_id => biblioentry.id)
@ziegler1969 = Citation.find_by_name("ziegler1969")
biblioentry = Biblioentry.find_by_xreflabel('stommel1983')
Citation.create(:name => "stommel1983", :user_id => @user.id,:biblioentry_id => biblioentry.id)
@stommel1983 = Citation.find_by_name("stommel1983")

