kind: Service
apiVersion: v1
metadata:
  name: holocene-service
  labels:
    app: holocene
spec:
  selector:
    app: holocene
  type: NodePort
  #type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
