apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: railsapp-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: railsapp
    spec:
      containers:
      - name: railsapp
        image: 127.0.0.1:30400/holocene:latest
        imagePullPolicy: Always
        args: ["rails s -p 3000 -b 0.0.0.0"]
        ports:
        - containerPort: 3000
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: railsapp-secrets
                key: secret-key-base
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: db-user
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: db-name
                key: name
          - name: RAILS_ENV
            value: production
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: RAILS_SERVE_STATIC_ASSETS
            value: "true"
          - name: REDIS_URL
            value: "redis://redis-master.default.svc.cluster.local"
          - name: REDIS_HOST
            value: redis-master.default.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password
