development:
  html_strip: true
  min_infix_len: 2


production:
  sql_range_step: 10000000
  mysql41: 9307
  html_strip: true
  min_infix_len: 2
  mysql41: 9313
  indices_location: <%= File.join(Rails.root, "db", "sphinx", "production") %>
  configuration_file: <%= File.join("/","home","deploy","apps","holocene","shared", "config", "production.sphinx.conf")%>
  log: <%= File.join("/","home","deploy","apps","holocene","shared", "log", "production.searchd.log") %>
  query_log: <%= File.join("/","home","deploy","apps","holocene","shared", "log", "production.searchd.query.log") %>
  binlog_path: <%= File.join("/","home","deploy","apps","holocene","shared", "tmp", "binlog", "production") %>
  pid_file: <%= File.join("/","home","deploy","apps","holocene","shared", "tmp", "pids", "production.sphinx.pid") %>

test:
  sql_range_step: 10000000
  mysql41: 9307
  html_strip: true
  min_infix_len: 2
  mysql41: <%= 9313 + ENV['TEST_ENV_NUMBER'].to_i %>
  indices_location: <%= File.join(Rails.root, "db", "sphinx", "test#{ENV['TEST_ENV_NUMBER']}") %>
  configuration_file: <%= File.join(Rails.root, "config", "test#{ENV['TEST_ENV_NUMBER']}.sphinx.conf")%>
  log: <%= File.join(Rails.root, "log", "test#{ENV['TEST_ENV_NUMBER']}.searchd.log") %>
  query_log: <%= File.join(Rails.root, "log", "test#{ENV['TEST_ENV_NUMBER']}.searchd.query.log") %>
  binlog_path: <%= File.join(Rails.root, "tmp", "binlog", "test#{ENV['TEST_ENV_NUMBER']}") %>
  pid_file: <%= File.join(Rails.root, "tmp", "pids", "test#{ENV['TEST_ENV_NUMBER']}.sphinx.pid") %>
