john = Character.find_by_name("John Allen Cummings")
john.update_attributes({:last_name=>"Cummings", :first_name=>"John", :middle_name=>"Allen", :age_at_son=>27, :birth_year=>78, :death_year=>147, :father_id=>nil})
Character.create({:last_name=>"Cummings", :first_name=>"James", :middle_name=>"Dimitri", :age_at_son=>29, :birth_year=>105, :death_year=>175, :father_id=>john.id})
Character.create({:last_name=>"Cummings", :first_name=>"Dimitri", :middle_name=>"John", :age_at_son=>32, :birth_year=>134, :death_year=>204, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Charles", :middle_name=>"James", :age_at_son=>32, :birth_year=>166, :death_year=>231, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Allen", :middle_name=>"Dimitri", :age_at_son=>26, :birth_year=>198, :death_year=>269, :father_id=>Character.last.id})

father = Character.last
Character.create({:last_name=>"Cummings", :first_name=>"George", :middle_name=>"Charles", :age_at_son=>24, :birth_year=>224, :death_year=>277, :father_id=>father.id})
Character.create({:last_name=>"Cummings", :first_name=>"Samuel", :middle_name=>"Allen", :age_at_son=>24, :birth_year=>248, :death_year=>301, :father_id=>father.id})

Character.create({:last_name=>"Cummings", :first_name=>"Michael", :middle_name=>"George", :age_at_son=>33, :birth_year=>272, :death_year=>342, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"William", :middle_name=>"Samuel", :age_at_son=>23, :birth_year=>305, :death_year=>375, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Christopher", :middle_name=>"Michael", :age_at_son=>25, :birth_year=>328, :death_year=>393, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"John", :middle_name=>"William", :age_at_son=>24, :birth_year=>353, :death_year=>420, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"James", :middle_name=>"Christopher", :age_at_son=>35, :birth_year=>377, :death_year=>440, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Dimitri", :middle_name=>"John", :suffix=>"II", :age_at_son=>29, :birth_year=>412, :death_year=>476, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Charles", :middle_name=>"James", :suffix=>"II", :age_at_son=>34, :birth_year=>441, :death_year=>507, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Allen", :middle_name=>"Dimitri", :suffix=>"II", :age_at_son=>30, :birth_year=>475, :death_year=>543, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"George", :middle_name=>"Charles", :suffix=>"II", :age_at_son=>26, :birth_year=>505, :death_year=>570, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Samuel", :middle_name=>"Allen", :suffix=>"II", :age_at_son=>25, :birth_year=>531, :death_year=>600, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Michael", :middle_name=>"George", :suffix=>"II", :age_at_son=>30, :birth_year=>556, :death_year=>619, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"William", :middle_name=>"Samuel", :suffix=>"II", :age_at_son=>34, :birth_year=>586, :death_year=>656, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Christopher", :middle_name=>"Michael", :suffix=>"II", :age_at_son=>27, :birth_year=>620, :death_year=>691, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"John", :middle_name=>"William", :suffix=>"II", :age_at_son=>24, :birth_year=>647, :death_year=>711, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"James", :middle_name=>"Christopher", :suffix=>"II", :age_at_son=>23, :birth_year=>671, :death_year=>737, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Dimitri", :middle_name=>"John", :suffix=>"III", :age_at_son=>29, :birth_year=>694, :death_year=>762, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Charles", :middle_name=>"James", :suffix=>"III", :age_at_son=>30, :birth_year=>723, :death_year=>791, :father_id=>Character.last.id})
Character.create({:last_name=>"Cummings", :first_name=>"Allen", :middle_name=>"Dimitri", :suffix=>"III", :age_at_son=>27, :birth_year=>753, :death_year=>823, :father_id=>Character.last.id})

