# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#characterization = CharacterCategory.create([
#  {name: "Physical Appearance"},{name: "Favorites"},{name: "Background"},
#  {name: "Family"}, {name: "Attitude"},{name: "Personality"},
#  {name: "Traits"}
#])

category = CharacterCategory.create({name: "Physical Appearance"})

attri = CharacterAttribute.create({name: "age", character_category_id: category.id})
  CharacterAttribute.create({name: "age_appearance", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "eye_color", character_category_id: category.id})
  CharacterAttribute.create({name: "glasses_contacts", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "hair_color", character_category_id: category.id})
  CharacterAttribute.create({name: "hair_style", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "weight", character_category_id: category.id})
attri = CharacterAttribute.create({name: "height", character_category_id: category.id})
attri = CharacterAttribute.create({name: "type_of_body", character_category_id: category.id})
attri = CharacterAttribute.create({name: "skin_tone", character_category_id: category.id})
  CharacterAttribute.create({name: "skin_type", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "shape_of_face", character_category_id: category.id})
attri = CharacterAttribute.create({name: "marks", character_category_id: category.id})
  CharacterAttribute.create({name: "freckles", character_category_id: category.id, related_id: attri.id})
  CharacterAttribute.create({name: "moles", character_category_id: category.id, related_id: attri.id})
  CharacterAttribute.create({name: "scars", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "predominate_feature", character_category_id: category.id})
attri = CharacterAttribute.create({name: "looks_like", character_category_id: category.id})
attri = CharacterAttribute.create({name: "healthy", character_category_id: category.id})
  CharacterAttribute.create({name: "why_not", character_category_id: category.id, related_id: attri.id})


category = CharacterCategory.create({name: "Favorites"})

attri = CharacterAttribute.create({name: "favorite_color", character_category_id: category.id})
attri = CharacterAttribute.create({name: "least_favorite_color", character_category_id: category.id})
  CharacterAttribute.create({name: "why", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "favorite_music", character_category_id: category.id})
attri = CharacterAttribute.create({name: "least_favorite_music", character_category_id: category.id})
  CharacterAttribute.create({name: "why", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "food", character_category_id: category.id})
attri = CharacterAttribute.create({name: "literature", character_category_id: category.id})
attri = CharacterAttribute.create({name: "expressions", character_category_id: category.id})
attri = CharacterAttribute.create({name: "expletives", character_category_id: category.id})
attri = CharacterAttribute.create({name: "mode_of_trans", character_category_id: category.id})
attri = CharacterAttribute.create({name: "daredevil_cautious", character_category_id: category.id})
  CharacterAttribute.create({name: "same_alone", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "habits", character_category_id: category.id})
attri = CharacterAttribute.create({name: "drinks", character_category_id: category.id})
  CharacterAttribute.create({name: "what", character_category_id: category.id, related_id: attri.id})
CharacterAttribute.create({name: "when_how_much", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "hobbies", character_category_id: category.id})
attri = CharacterAttribute.create({name: "rainy_day", character_category_id: category.id})

category = CharacterCategory.create({name: "Background"})

attri = CharacterAttribute.create({name: "hometown", character_category_id: category.id})
attri = CharacterAttribute.create({name: "type_of_childhood", character_category_id: category.id})
attri = CharacterAttribute.create({name: "first_memory", character_category_id: category.id})
attri = CharacterAttribute.create({name: "most_import_childhood", character_category_id: category.id})
  CharacterAttribute.create({name: "why_most_import", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "education", character_category_id: category.id})
attri = CharacterAttribute.create({name: "religion", character_category_id: category.id})
attri = CharacterAttribute.create({name: "finances", character_category_id: category.id})

category = CharacterCategory.create({name: "Family"})

attri = CharacterAttribute.create({name: "mother", character_category_id: category.id})
  CharacterAttribute.create({name: "relationship_with", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "father", character_category_id: category.id})
  CharacterAttribute.create({name: "relationship_with", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "siblings", character_category_id: category.id})
  CharacterAttribute.create({name: "how_many", character_category_id: category.id, related_id: attri.id})
  CharacterAttribute.create({name: "birth_order", character_category_id: category.id, related_id: attri.id})
  CharacterAttribute.create({name: "relationship_with_each", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "child_of_siblings", character_category_id: category.id})
attri = CharacterAttribute.create({name: "extended_family", character_category_id: category.id})
attri = CharacterAttribute.create({name: "close", character_category_id: category.id})
  CharacterAttribute.create({name: "why_why_not", character_category_id: category.id, related_id: attri.id})

category = CharacterCategory.create({name: "Attitude"})

attri = CharacterAttribute.create({name: "most_at_ease", character_category_id: category.id})
attri = CharacterAttribute.create({name: "ill_at_ease", character_category_id: category.id})
attri = CharacterAttribute.create({name: "priorities", character_category_id: category.id})
attri = CharacterAttribute.create({name: "philosophy", character_category_id: category.id})
attri = CharacterAttribute.create({name: "feel_about_self", character_category_id: category.id})
attri = CharacterAttribute.create({name: "past_failures", character_category_id: category.id})
  CharacterAttribute.create({name: "why", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "one_wish", character_category_id: category.id})
  CharacterAttribute.create({name: "why", character_category_id: category.id, related_id: attri.id})

category = CharacterCategory.create({name: "Personality"})

attri = CharacterAttribute.create({name: "great_strength", character_category_id: category.id})
attri = CharacterAttribute.create({name: "great_weakness", character_category_id: category.id})
attri = CharacterAttribute.create({name: "soft_spot", character_category_id: category.id})
  CharacterAttribute.create({name: "obvious_to_others", character_category_id: category.id, related_id: attri.id})
  CharacterAttribute.create({name: "how_hide", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "biggest_vulnerability", character_category_id: category.id})

category = CharacterCategory.create({name: "Traits"})

attri = CharacterAttribute.create({name: "optimist_pessimist", character_category_id: category.id})
  CharacterAttribute.create({name: "why", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "introvert_extrovert", character_category_id: category.id})
  CharacterAttribute.create({name: "why", character_category_id: category.id, related_id: attri.id})
attri = CharacterAttribute.create({name: "drives_motivations", character_category_id: category.id})
attri = CharacterAttribute.create({name: "talents", character_category_id: category.id})
attri = CharacterAttribute.create({name: "extremely_skilled", character_category_id: category.id})
attri = CharacterAttribute.create({name: "extremely_unskilled", character_category_id: category.id})
attri = CharacterAttribute.create({name: "good_characteristics", character_category_id: category.id})
attri = CharacterAttribute.create({name: "character_flaws", character_category_id: category.id})
attri = CharacterAttribute.create({name: "mannerisms", character_category_id: category.id})
attri = CharacterAttribute.create({name: "peculiarities", character_category_id: category.id})
attri = CharacterAttribute.create({name: "biggest_regret", character_category_id: category.id})
attri = CharacterAttribute.create({name: "minor_regrets", character_category_id: category.id})
attri = CharacterAttribute.create({name: "darkest_secret", character_category_id: category.id})
  CharacterAttribute.create({name: "anybody_know", character_category_id: category.id, related_id: attri.id})
  CharacterAttribute.create({name: "char_tell_them", character_category_id: category.id, related_id: attri.id})
  CharacterAttribute.create({name: "how_find_out", character_category_id: category.id, related_id: attri.id})
